### ISSUE TITLE
Zigbee msg for Selectorswitch trigger scripts only once when multiple identical msg's are sent

### ISSUE THREAD

**Issue by wifiminime** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#125]
**Issue description**
Put general information here
zigbee2mqqt plugin for domoticz:

Philips Hue dimmer switch, press same button multiple times --> scripts only triggered once because device is mapped to Selector switch and state does not change.
For instance: msg: up-press is used to increase light, but you can only do this once...
Mqqt message is there, not propagated to domoticz because state of selector switch does not change, suppressed in zigbee2mqqt plugin for domoticz

What did you expect to happen?
I expect that when i have a zigbee device that has pushbuttons(!) that the corresponding device in domoticz also behaves like this: after button is released this will also be effective in the state of the domoticz device. (I do realize that this might cause problems for scenarios like press-hold-release)

How to reproduce it (minimal and precise)?
use Zigbee2mqqt plugin for domoticz, add a pushbutton zigbee device that maps on a selector switch (Mi aqara / philips dimmer switch).
Press button (single click) ,wait, press button again, wait, press button again etc
Second and following button clicks will not be shown in domoticz log, and will not trigger scripts.

**Additional information**
Zigbee2MQTT version:
latest (updated 27-06-2019)
Python version:?
Domoticz version: 4.10717
Plugin version:
latest (updated 27-06-2019)

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by bricamac** [comment]
Yep I have notice this issue. 

We could the event into the zigbee2mqtt log:

For example the action "up-press" it's present to two times into zigbee2mqtt log, we could motice that 
the brightness value increase...
7/1/2019, 10:59:05 PM - info: MQTT publish: topic 'zigbee2mqtt/Telecommande Philips salon', payload '{"counter":1,"linkquality":47,"battery":100,"brightness":50,"action":"up-press","duration":0}'
7/1/2019, 10:59:05 PM - info: Zigbee publish to device '0x00178801035e2085', genLevelCtrl - moveToLevelWithOnOff - {"level":244,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null
7/1/2019, 10:59:13 PM - info: MQTT publish: topic 'zigbee2mqtt/Telecommande Philips salon', payload '{"counter":1,"linkquality":44,"battery":100,"brightness":100,"action":"up-press","duration":0}

But lua see only the first press because for LUA no change between to press on key "up-press"
2019-07-01 22:59:05.665  Status: LUA: Device based event fired on 'Zigbee - Telecommande', value 'up-press'
2019-07-01 22:59:05.665  Status: LUA: -------------------
2019-07-01 22:59:05.665  Status: LUA: Set dimmer to 96%
2019-07-01 22:59:05.669  Status: EventSystem: Script event triggered: test
2019-07-01 22:59:06.681  Status: Executing script: /opt/domoticz/scripts/domoticz_main
2019-07-01 22:59:07.225  Status: Executing script: /opt/domoticz/scripts/domoticz_main
2019-07-01 22:59:10.530  (RFXCOM) Temp (Garage2)
2019-07-01 22:59:14.446  (UPS) Pushing 'onHeartbeatCallback' on to queue
2019-07-01 22:59:14.486  (UPS) Processing 'onHeartbeatCallback' message
2019-07-01 22:59:14.486  (UPS) Calling message handler 'onHeartbeat'.

Thanks in advance for you help.

**Comment by bricamac** [comment]
I found  a temporary solution.  I have a have an small modification into the code "hue_dimmer_switch.py" to create also a  dimmer switch associated to Hue Philips dimmer switch.

I seem working fine.


[hue_dimmer_switch.py.zip](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/files/3352077/hue_dimmer_switch.py.zip)

**Comment by wifiminime** [comment]
Hi,

thanks for the work so far, tested it, seems to be working, one little thing (i can live with it but still...)

I do not seem to be able to get my lamp in sync with the dimmer switch when i change lamp brigthness via my phone (hue lamp, with its own brightness). My script is set to when i use dimmer switch to control lamp brightness, lamp will get brightness of switch.  So now i change the brightness of the lamp via phone and the level of lamp no longer matches the level of dimmerswitch --> next press on dimmerswitch will set it back again to the level of the dimmerswitch (instead of decreasing / increasing brightness 1 step).

I tried to  match them but could not get it to work because i am not able to change the level of the dimmer switch via my script ... any thoughts on this?

**Comment by bricamac** [comment]
Hi,

I will try to take a look of this problem, but It seems that we could modify the brightness value stored into the philips remote.

best  regards.

**Comment by antoninocanta** [comment]
Hello Everyone,
I have the same issue with my xiaomi aqara double switch (wireless version).  When I press the same button multiple time, the associated script run only once.  I need to push the other button to make the first workable...
Do you have a solution that I can apply in the source code to solve ?
I am very grateful for your remarkable work.  Thank you everyone.
Kind regards.

Antonino.

**Comment by stas-demydiuk** [comment]
@antoninocanta could you please update plugin and check if my solution works for you?

**Comment by antoninocanta** [comment]
Hello master stas-demydiuk,
Sorry for the delay of my answer,
This update fix the bug perfectly ^^
Thank you for your work, the code is very clean and pro ;)
Kind regards.
Antonino.
