### ISSUE TITLE
More support for Xiaomi Aqara Sensor DJT11LM

### ISSUE THREAD

**Issue by SargonofAssyria** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#305]
This device gives much more info then imported to Domoticz.
I only get 4 devices into Domoticz.
It would be nice to get at least the 'strength' into Domoticz

**Additional information**
Zigbee2MQTT version:  zigbee2mqtt version 1.13.0-dev (commit #e792f8b)
Python version: 3.7.3
Domoticz version: 4.10717
Plugin version: 0.2.0 latest

`info  2020-05-04 12:06:19: MQTT publish: topic 'zigbee2mqtt/VibrationSensor', payload '{"battery":100,"voltage":3015,"linkquality":111,"last_seen":"2020-05-04T12:06:19+02:00","angle":87,"angle_x":-1,"angle_y":87,"angle_z":3,"angle_x_absolute":91,"angle_y_absolute":3,"strength":20,"action":"vibration"}'
info  2020-05-04 12:06:19: MQTT publish: topic 'zigbee2mqtt/VibrationSensor', payload '{"battery":100,"voltage":3015,"linkquality":111,"last_seen":"2020-05-04T12:06:19+02:00","angle":87,"angle_x":-1,"angle_y":87,"angle_z":3,"angle_x_absolute":91,"angle_y_absolute":3,"strength":20,"action":""}'
info  2020-05-04 12:06:19: MQTT publish: topic 'zigbee2mqtt/VibrationSensor/action', payload 'vibration'
`

**Comment by kitopopo** [comment]
hi Dear friend,

Yes , i would need the strenght vibration also, is  very interesting for can close my awinds 
depending on the force of the wind, we will be waiting for the implementation if it is possible, Thanks

**Comment by stas-demydiuk** [comment]
Would you like to see just strength sensor or maybe it make sense to create TextSensor with all JSON values?

**Comment by kitopopo** [comment]
Hi, sorry for the delay. I think that for me a force sensor would be good for me to be able to make a script in which I can put: 

if domoticz.devices('strenght').value  >= 155 then close awnings.

I don't  know if other users need more possibilities.. Thanks for your job,.

Best regards

**Comment by SargonofAssyria** [comment]
I all ready use a custom sensor with Axis label 'trilling' by a nodered flow.
It is working fine, but a direct device from zigbee2mqtt would be nice.
All the rest of those values does not make very much sense to me and if then I make a flow.

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check

**Comment by kitopopo** [comment]
hi dear friend,

Yes , i check some minutes ago and the strenght value appears correctly and show the value correctly in the firs attempt. Nice work friend. Wonderful.
In the list of the devices appear a btprc to 100% value, whats means this value? thanks for the good job. nice

**Comment by stas-demydiuk** [comment]
> In the list of the devices appear a btprc to 100% value, whats means this value?

Yes, it is battery percentage

**Comment by SargonofAssyria** [comment]
Tnx, it works.

**Comment by kitopopo** [comment]
dear friend @stas-demydiuk,

First of all thank you very much for adding the strenght value to domoticz. I hope you are okay.
I have thought that to have better control over the awnings with the vibration sensor, it could be interesting to add the information of the angles (if possible) since they show updated update in each vibration, instead the strenght value is updated every 5 minutes. I apologize for not thinking about this when we include only the strenght value. I would be grateful. Thank you very much for your work. a cordial greeting

"angle":5,"angle_x":25,"angle_y":-44,"angle_z":35,"angle_x_absolute":65,"angle_y_absolute":134,"strength":55}

**Comment by SargonofAssyria** [comment]
Then you will have to figure out how it is presented in Domoticz.
I think it should then be something like a custom sensor with axis in degrees, but then you get 6 devices. Then something like dzVents should process all those devices to a end result/action.
Or just use MQTT and Nodered?

**Comment by kitopopo** [comment]
In domoticz i have the followings devices detected:
stgth, btperc, action , cell and signal. I need one more device for the angles.

The zigate plugin has a device same of the strenght but only for the angle. We can see this link, Please read the link for see the orientation device:

> https://github.com/Koenkk/zigbee2mqtt/issues/2258

I think that is possible ad a new device detected with the name 'orientation: X,Y and z values.

Maybe @stas-demydiuk can add orientation device? Thanks in advanced.

**Comment by stas-demydiuk** [comment]
Yes, I can add text sensor device as in zigate plugin if it suits your needs. I think even better would be to use JSON as a value, so it easily can be converted to lua table in dzVents or Lua script

@kitopopo , @SargonofAssyria what do you think?

**Comment by SargonofAssyria** [comment]
Beter to use json I guess. But like I wrote before also the angle's data is not coming instantly.
I just changed the angle of one of the axis just a little bit and no MQTT message came.
So I do not think that @kitopopo needs will be fulfilled. But then again it does not harm either.

**Comment by kitopopo** [comment]
> Yes, I can add text sensor device as in zigate plugin if it suits your needs. I think even better would be to use JSON as a value, so it easily can be converted to lua table in dzVents or Lua script
> 
> @kitopopo , @SargonofAssyria what do you think?

Hi dear friend. Sorry by the delay . Is possible add normal value x,y,z in decimal number from 0 to 999 likes to vibration sensor? I havent started yet to works with json values table in domoticz.  What do you think? I don't know if json have advantages. Thanks in advanced

**Comment by SargonofAssyria** [comment]
Json has advantages, easier to get the separate numbers.
But please don't calculate with the numbers, use them as they come from the device.
@kitopopo X,Y,Z data is not coming instantly, so does it serve your purpose?

**Comment by kitopopo** [comment]
> Json has advantages, easier to get the separate numbers.
> But please don't calculate with the numbers, use them as they come from the device.
> @kitopopo X,Y,Z data is not coming instantly, so does it serve your purpose?

Sorry, after some hours when i arrive at home i willconfirm. Now i am in the work. I think that my values of angle arrive instantly. I confirm at night. Thanks

**Comment by SargonofAssyria** [comment]
Put the device upright on a flat table with the reset button up.
Turn the device slowly around its z-axis, you will see no MQTT message.
Same when you put it flat on the table with the small LED facing up.
Slow rotation does not send a MQTT message.
Tilt, vibration and drop do.

**Comment by kitopopo** [comment]
> Yes, I can add text sensor device as in zigate plugin if it suits your needs. I think even better would be to use JSON as a value, so it easily can be converted to lua table in dzVents or Lua script
> 
> @kitopopo , @SargonofAssyria what do you think?

I use domoticz. A friend from domoticz group said me that no is possible use json in domoticz. I'd rather a normal value. Thanks in advanced

**Comment by stas-demydiuk** [comment]
I've added sensor with JSON value, could someone pleas test it.

@kitopopo you can try to parse JSON in LUA (dzVents) script using this solution
https://stackoverflow.com/questions/42139363/how-to-parse-json-in-lua

**Comment by kitopopo** [comment]
> He agregado un sensor con valor JSON, ¿alguien podría probarlo?
> 
> @kitopopo puede intentar analizar JSON en script LUA (dzVents) usando esta solución
> https://stackoverflow.com/questions/42139363/how-to-parse-json-in-lua

hi, dear friend @stas-demydiuk ,

using Json @SargonofAssyria  has the complete table, but we with domoticz need the value. We need the values ​​x, y, z in numerical format. Could you add this?  They confirm to me in the domoticz group again that we need the values, the tables do not serve us in domoticz. we would be very grateful if we can get the value of x, y, z. in advance and kind regards

**Comment by kitopopo** [comment]
> I've added sensor with JSON value, could someone pleas test it.
> 
> @kitopopo you can try to parse JSON in LUA (dzVents) script using this solution
> https://stackoverflow.com/questions/42139363/how-to-parse-json-in-lua

hello @stas-demydiuk ,

I have restarted domoticz and the new angle sensor does not appear. I only see the 5 devices mentioned above. I have been able to read the strenght values ​​through Json and these values ​​appear correctly, but since no angle sensor appears I cannot read these values. Thanks again

**Comment by kitopopo** [comment]
sorry, i forget update the plugin. I will try now

**Comment by kitopopo** [comment]
yes, the sensor appear, i can read the following values:

```
{
	"ActTime" : 159xxxxx,
	"AstrTwilightEnd" : "23:15",
	"AstrTwilightStart" : "04:22",
	"CivTwilightEnd" : "21:46",
	"CivTwilightStart" : "05:50",
	"DayLength" : "14:51",
	"NautTwilightEnd" : "22:28",
	"NautTwilightStart" : "05:09",
	"ServerTime" : "2020-05-26 00:35:09",
	"SunAtSouth" : "13:48",
	"Sunrise" : "06:23",
	"Sunset" : "21:14",
	"app_version" : "2020.2 (build 12086)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "",
			"Description" : "",
			"Favorite" : 0,
			"HardwareID" : 22,
			"HardwareName" : "zigbe2mqtt",
			"HardwareType" : "Zigbee2MQTT",
			"HardwareTypeVal" : 94,
			"HaveTimeout" : false,
			"ID" : "0x00158d000xxxxx_angle",
			"LastUpdate" : "2020-05-26 00:34:40",
			"Name" : "zigbe2mqtt - Sensor vibracion (Angle)",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"ShowNotifications" : false,
			"SignalLevel" : "-",
			"SubType" : "Text",
			"Timers" : "false",
			"Type" : "General",
			"TypeImg" : "text",
			"Unit" : 124,
			"Used" : 0,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "509"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}
```
any data appear, thanks anyway for adding the angle even though I can't read the data for now I will learn. best regards

**Comment by SargonofAssyria** [comment]
This is the data I got from the new created text device, it can easily be processed.
`{"angle": 89, "angle_x": -1, "angle_y": 87, "angle_z": 3, "angle_x_absolute": 91, "angle_y_absolute": 3}`
But like I wrote before it does not change when I slowly rotate the device.
@kitopopo did you investigate that.
@kitopopo  please share the link where this is discussed in the Domoticz forum.

**Comment by kitopopo** [comment]
> Tnx, @stas-demydiuk This is the data I got from the new created text device, it can easily be processed.
> `{"angle": 89, "angle_x": -1, "angle_y": 87, "angle_z": 3, "angle_x_absolute": 91, "angle_y_absolute": 3}`
> But like I wrote before it does not change when I slowly rotate the device.
> @kitopopo did you investigate that. B.t.w. looking at 'Data', you did not move the device.
> @kitopopo please share the link where this is discussed in the Domoticz forum.
> 
> Parsing json in dzVents is even more simple.
> https://www.domoticz.com/forum/viewtopic.php?f=59&t=32062&p=242622&hilit=parse+json#p242622

Hi dear friend @SargonofAssyria 

About Json , I have not discussed it in domoticz forum, is a private telegram group , have near of 400 users. I talked about it in the group and most told me they preferred a value. With a decimal value is very easy to implement angles in the script. others telegram users told me that domoticz and JSON is very limited compared others systems. 

So I have looked over the json example script in dzvents, but I do not see any device anywhere or idx

The truth that, I requested that the angles to @stas-demydiuk  be included and also commented yesterday that it was a numerical value,  It has taken me more than a year that they included the strenght sensor in domoticz, I have spoken with mr koenkk and with mr gimocuz, in the end I have succeeded I do not understand why the sensor was created in Json if I requested a numerical value. Mr @stas-demydiuk could have created 2 angle sensors to satisfy both of us, 

hey, now it is included in Json, I will investigate to see if these data can be obtained in dzvents because I do not see it clearly. But I did not blame him, he made the request and his work correctly, I thank him again for his work.  Thank you @stas-demydiuk yo was very kind to attend to the request.

I hope you @SargonofAssyria  that you enjoy your sensor with json as I still can't. my work takes up a lot of time, when I can find out more time i will read about this if is possible to do it in dzvents. a cordial greeting

@SargonofAssyria You can close this issue if you want , my issue for include the vibration sensor was 5 hours after yours, you got ahead of me. I will deal with Json, don't worry. have a nice day. thanks

**Comment by stas-demydiuk** [comment]
@kitopopo could you please share what kind of script you'd like to implement with this angles data?

**Comment by SargonofAssyria** [comment]
In json it's only 1 device which data can be process what ever you like.
Numeric values will give 6 devices which you have to monitor one by one, because you cannot know which axis will change.
But more important I found out that axis data will NOT change if you gently rotate the device.
As far as I can see only one of the actions will trigger new data, same as for strength. Did you check that? Because if it is true then you are stuck with the same problem, that if "motion" (slowly) of the device will NOT give you any new data set.
Did you check the link I gave you about json in Domoticz? One (or more) of those 400 Telegram users should be able to help you. But better ask the question on the Domoticz forum.
I could help you there too to get the right dzVents script for you purpose.

**Comment by kitopopo** [comment]
> @kitopopo could you please share what kind of script you'd like to implement with this angles data?


Hello dear friends,

My vibration sensor and zigbemqtt only updates the strenght value every exact 5 minutes. But instead the sensor does update the 6 values ​​instantly after a movement: agle, x, y, z, absolute x and absolute y.

My idea was as follows. When my awning is open it has an exact value angle, x, y, z, absolute x and absolute y in the open position. 

The structure of the script is simple:

If any of these values ​​changes due to the wind, it closes awnings.

I think my idea is not successful. Moving the arm of the awning simulating the force of the wind I always get the same values. It appears that the vibration sensor sends all angle values ​​when it stops, and when it stops these values ​​are the same as when the awning is open (no wind). 

I apologize for not having done these tests before requesting to include these values, but as I saw that it updated all the values ​​every 2 or 3 seconds I thought that as soon as the awning moved it would notify the new angles but it seems that it only notifies them when the sensor stops moving and these values ​​match the initial values. that's why I needed the values ​​in decimal value to make a very simple script. 
Anyway now we have the Json values ​​in case we need to use them for any other future idea of ​​some element that moves but not an awning.

I will have to investigate how to reduce the refresh time of the strenght value (this value as you did in decimal value works incredibly well for me. According to mr koenkk , the value of strenght depends on the firmware of the vibration sensor, maybe doing a hardware modification likes to the motion sensor we can reduce the refresh time ( according to online tutorials). 

Thank you very much @stas-demydiuk and @SargonofAssyria  for your attention and especially @stas-demydiuk  for their dedication and work in including strenght angles and value.,  they have been both very friendly at all times. Thanks again.
