### ISSUE TITLE
SONOFF SNZB-04

### ISSUE THREAD

**Issue by Emmanuel-FR** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#378]
**Device description**
SONOFF Door Sensor SNZB-04

**MQTT message with device information**

{"ieeeAddr":"0x00124b001b7d03f2","type":"EndDevice","networkAddress":22599,"model":"SNZB-04","vendor":"SONOFF","description":"Contact sensor",        "friendly_name":"Door_Sensor_3","manufacturerID":0,"manufacturerName":"eWeLink","powerSource":"Battery","modelID":"DS01","hardwareVersion":1,"dateCode":"20191107","lastSeen":1596230570851}

**MQTT messages from device**
{"battery":100,"voltage":3200,"linkquality":34,"contact":true,"tamper":false,"battery_low":false}

{"battery":100,"voltage":3200,"linkquality":36,"contact":false,"tamper":false,"battery_low":false}

**MQTT state change commands**
If device supports state change put MQTT topics + payload examples to change device state here

**Comment by stas-demydiuk** [comment]
Done, could you please update plugin and check

**Comment by Emmanuel-FR** [comment]
That was fast !

I updated the plugin. The sensor shows up OK in the Z2M devices list with its devices , but there are two minor issues when compared to xiaomi aquara door sensors : 
- the sensor appears as a "contact" and not a "door contact" sensor (not the same icon, it's a double arrow)
- I think the values are inversed, it appears open when close and closed when open.

I fear I'm not proficient enough with programming to check out your code, will give it a try tonite.

Thanks a lot, even if I had found a way with node red, it's much nicer this way !

**Comment by Emmanuel-FR** [comment]
Ok, I checked the code. I compared the implementation of aquara door sensor and from what I understand (not much), there is indeed a difference with importation : SensorMagnet is imported and not ContactSensor.

I guess they work with the opposite boolean stuff.

**Comment by stas-demydiuk** [comment]
You probably can change the type to desired on device settings page in Domoticz

**Comment by Emmanuel-FR** [comment]
Hi,

Well, I did it, so that's ok for the icon but the remaining issue is that the state is wrong :

Closed shows as Open (and vice-versa).

Regards

----- Mail original -----
De: "Stanislav Demydiuk" <notifications@github.com>
À: "stas-demydiuk/domoticz-zigbee2mqtt-plugin" <domoticz-zigbee2mqtt-plugin@noreply.github.com>
Cc: "Emmanuel-FR" <emmanuel.rousseau6@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Samedi 15 Août 2020 15:13:40
Objet: Re: [stas-demydiuk/domoticz-zigbee2mqtt-plugin] SONOFF SNZB-04 (#378)





You probably can change the type to desired on device settings page in Domoticz

**Comment by hughb8on** [comment]
I have one of these and agree that as currently coded it reports the Open/Close state incorrectly.

This is because it is defined as a ContactSensor when it should be defined as a DoorContactSensor 

devices/sensor/door_contact.py is exactly the same as devices/sensor/contact.py EXCEPT it inverts the logic, which is what we need here.

So, if we change adapters/sonoff/SNZB-04.py to look like this, it works as we want: -

from adapters.contact_adapter import ContactAdapter
from devices.sensor.door_contact import DoorContactSensor

class SNZB04(ContactAdapter):
    def __init__(self, devices):
        super().__init__(devices)
        self.devices.append(DoorContactSensor(devices, 'sensor', 'contact'))

I have tested this. My coding knowledge is inadequate to be sure there aren't other implications so I'm not going to raise a pull request. In particular I am not sure what effect removing the 'tamper' stuff will have; I believe these devices don't actually have any tamper-detect hardware anyway, so maybe it doesn't matter.

Incidentally, I believe these four Sonoff devices are just white-label versions of Ewelink devices already defined in the plugin, so 1) we probably didn't need a separate folder for them, they could have just been added into the Ewelink definitions, and 2) the Ewelink equivalent device (RHK06) likely also needs to be defined as a door_contact.

**Comment by hughb8on** [comment]
Later note: I have reverted to the original SNZB-04.py. My version does indeed report the state Open/Closed state correctly but it has the side-effect of interpreting Tamper heartbeat messages as state changes for the Contact itself. At least, that's what I surmise, but as I said above, I don't have the knowledge to be sure.

**Comment by stas-demydiuk** [comment]
I updated the device, could you please check? (you'll need to remove the existing one from Domoticz first)

**Comment by Emmanuel-FR** [comment]
It works perfectly for me now, thank you very much !!!

**Comment by hughb8on** [comment]
Me too. Thank you!
