### ISSUE TITLE
Missing motion detector (HG06335) (lidl

### ISSUE THREAD

**Issue by noci2012** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#489]
**Device description**
Silvercrest Motion sensor, SMSZ 1 A1

**Zigbee2mqtt page**
https://www.zigbee2mqtt.io/devices/HG06335.html

**MQTT message with device information**
See above

**MQTT messages from device**
See above

**MQTT state change commands**
See Above

**Comment by Melissen71** [comment]
When will this device be present in Domoticz?  Also boughed one, it works on my RaspberryPi, but motion-sensort doesn't make a 'switch/device' in Domoticz, so can't use it now

**Comment by salopette** [comment]
So this detector works for me, but there is always an error due to the battery.

`2020-12-08 20:06:15.975 Error: (z2m) BWM WC: can not process binary item "battery_low"
`

**Comment by Oizopower** [comment]
I have added a pull request for the motion sensor, i have it working in my own domoticz right now.
See: #498

**Comment by LaurentiuGrama** [comment]
Hi,
I added manually the sensor and is working for me too

![image](https://user-images.githubusercontent.com/10025713/101817933-d4843a00-3b2b-11eb-92f5-59068ad837d6.png)
I want to make a small remark. Can we remove the Voltage parameter because is not transmitted? Or in this case, Voltage is true or farse and represents battery_low?

**Comment by platte-73** [comment]
How did get the motion sensor working in domoticz. Can someone tell me how to Manuel add it
