### ISSUE TITLE
Plugin is freezing

### ISSUE THREAD

**Issue by loglux** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#546]
**Issue description**
![image](https://user-images.githubusercontent.com/37578325/104093422-55953500-5282-11eb-9199-08a7778198d4.png)

**Additional information**
Zigbee2MQTT version:  version 1.17.0 (commit #07cdc9d)
Python version:  docker
Domoticz version: 2020.2 (build 12738)
Plugin version:  name="Zigbee2MQTT" version="0.2.1"

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs
No logs

**Comment by rolfie23** [comment]
This happen to me also, is happens because Domoticz starts before the Zigbee2MQTT instance is taking much longer to start. After 1 minute after reboot I disable the Zigbee2MQTT plugin and enable it. After that everything works as normal!

**Comment by loglux** [comment]
Turned off Zigbee2mqtt plugin and turned on it after 5 min. 
The same picture.

**Comment by Anjerlaan** [comment]
With Zigbee2mqtt 1.17.0 you should use v3 of the domoticz-Zigbee2mqtt-plug-in.
First remove adapter from domoticz hardware than upgrade to v3, and add adapter again.

Z2M 1.17.0 uses a new api, one of the new things is that the functions of unknown devices are now exposed. Also the path which gets the devices list is changed to what it should always have been...this is why v 0.2.1 does not show the devices list, because it is still looking in the old path. 

Version v3 is updated for this.

v3 also should automatically expose new devices instead of asking support for a new device, but it has still errors for several device types.

Already supported devices are still recognized by v3, so if all your devices are configured in the adapter folder, then most of them should work properly.

But v3 has still some errors which need to be solved to make it work properly with Z2M 1.17.0
Sadly the plug-in developer is not often online lately

**Comment by loglux** [comment]
Used the latest version of the plugin
git clone https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt

**Comment by Anjerlaan** [comment]
And did you remove first the plug-in from the hardware page...and then a clean install? That appears to be quite evident

**Comment by loglux** [comment]
Yes. Removed, deleted plugin's folder and installed a new one from scratch.
The situation became even worse than it was before.

**Comment by Anjerlaan** [comment]
Strange, on which hardware and operating system are you running Z2M and Domoticz?

**Comment by loglux** [comment]
debian 10, intel celeron, official docker from docker hub.

**Comment by Anjerlaan** [comment]
I have a Rpi with raspbian Buster, so I can’t compare.
And Z2M is running stable?
Did you enable the web frontend in the configuration.yaml?

**Comment by loglux** [comment]
Tested Z2M on HASS. Even delays have gone. So starting to migrate to HA from Domoticz. 

> Did you enable the web frontend in the configuration.yaml?
No. Even didn't hear that they have one.

**Comment by Anjerlaan** [comment]
> This happen to me also, it happens because Domoticz starts before the Zigbee2MQTT instance which is taking much longer to start. After 1 minute after reboot I disable the Zigbee2MQTT plugin and enable it. After that everything works as normal!

I also had this problem, but solved it by delaying the startup of domoticz with 20 seconds in domoticz.sh
https://www.domoticz.com/forum/viewtopic.php?t=30846

sudo nano /etc/init.d/domoticz.sh

**Comment by Anjerlaan** [comment]
> Tested Z2M on HASS. Even delays have gone. So starting to migrate to HA from Domoticz.
> 
> > Did you enable the web frontend in the configuration.yaml?
> 
> No. Even didn't hear that they have one.

https://www.zigbee2mqtt.io/information/frontend.html

Such a nice feature!

**Comment by Anjerlaan** [comment]
> Tested Z2M on HASS. Even delays have gone. So starting to migrate to HA from Domoticz.
> 
This might be working without delays because you have installed HA after Z2M, and domoticz probably before Z2M, this is why I have a startup delay for domoticz

**Comment by loglux** [comment]
'probably' is a keyword that leads to a completely wrong conclusion.
I think it's a time to leave Domoticz. They stuck in the past and stay behind HA if we take a look at supported integrations.
Z2M is just a last drop. I guess my issue is also related to Domoticz itself.

**Comment by loglux** [comment]
Closing the thread as I moved from Domoticz to Home Assistant and don't have the issue anymore.
