### ISSUE TITLE
Temp+hum (*_th) devices removed(?)/stopped updating for Aqara WSDCGQ11LM

### ISSUE THREAD

**Issue by odelma** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#728]
**Issue description**
I went ahead and updated to the latest version. It seems that now the temp+hum (*_th) devices are not updating anymore for at least WSDCGQ11LM, possibly this device type removed altogether. This was the primary device I was using. Also some of the other "legacy" devices are not updating but they are not critical from my viewpoint:
![image](https://user-images.githubusercontent.com/10372952/138262330-09d1ff50-25b7-4936-857f-055b0ce9cc50.png)

Can we get the temp+hum device back?

**Additional information**
Zigbee2MQTT version: updated 21.10.2021
Python version: 3.7.3
Domoticz version: updated 21.10.2021 (Version: 2021.1 (build 13738))
Plugin version: updated 21.10.2021

**Comment by odelma** [comment]
Thanks a lot for the tip(/probable solution). It seems that now after several hours new set of temp+hum devices were created that are also updating 👍

I wonder why it went like this. Also the new voltage sensor show 3000V instead of 3.000V earlier 😄  - but that is minor…

**Comment by sammyke007** [comment]
Maybe re-open this issue?
I've updated too to the latest commit and indeed, the _th devices from the WSDCGQ11LM devices stopped from being updated.
The above code might work, but gets lost on next updates.

**Comment by sammyke007** [comment]
The WSDCGQ11LM device has temp + hum + press. In the past, the plugin created both "temp + hum" and "temp + hum + press" devices (and each one individual too). After the commit mentioned above, it only creates a "temp + hum + press" device. Is it possible @stas-demydiuk to also create a "temp + hum" device next to it?

The voltage also indeed seems to be off by x1000 (3000V instead of 3.0V)
