### ISSUE TITLE
Added switch does not show up in group/scene domoticz when pressed

### ISSUE THREAD

**Issue by tonbor** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#792]
**Issue description**
Put general information here
Want to run ventilator in attic from bathroom with a Aqara Wireless Remote Switch (Mini) Zigbee. Try to make a scene with activation of ventilator with 433mhz switch in the attic to ventilator. So when Wireless Remote Switch is pushed it will go on, twice the switch it well stop. Have added attic switch to devices ok, adding Aqara Wireless Remote Switch to activate devices fails. The push switch is not to be picked up by domoticz, the log op the push switch is ok, for every push. Some help?

**Additional information**
Zigbee2MQTT version: latest
Python version: 3.7
Domoticz version: 2022.1
Plugin version: latest beta

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by odelma** [comment]
How have you set the it to activate the switch? I fail to understand how a scene would be needed here (scene is a collection of devices that will be set to specific status when scene is triggered). You need to use the event system (Blockly, Lua, dzVents) or in theory via REST api by setting the http-command to actions behind the switch.

**Comment by tonbor** [comment]
Example that I implemented in scene: doorswitch closed (rfxcom) -> light
off (tasmota switch)

Other one: light on rfxcom button -> zwave plug on (light on)

Op do 14 apr. 2022 12:01 schreef odelma ***@***.***>:

**Comment by odelma** [comment]
Right, so you are using the "activation device" in the scene? I overlooked this as I do not use the activation device, I only use scenes as push buttons or trigger them from event system.

It looks to me that "activation device" only supports 433Mhz devices (which you can teach). With zigbee switches the options are (to my understanding) what I stated above. Maybe the easiest would be that you click the edit button of the remote switch and for the actions set something like:
Click: http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=1234&switchcmd=On
Double-click: http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=1234&switchcmd=Off

You need to set idx= the idx of your attic switch and set the domoticz port to url correct if it is something else than 8080.

A bit like in this example I found online:
![image](https://user-images.githubusercontent.com/10372952/163368484-0eb9d675-9dcf-4a9b-b79a-9c9615d04eaa.png)
In your case you should see something like "click" and "double-click" instead of

**Comment by tonbor** [comment]
> Right, so you are using the "activation device" in the scene? I overlooked this as I do not use the activation device, I only use scenes as push buttons or trigger them from event system.
> 
> It looks to me that "activation device" only supports 433Mhz devices (which you can teach). With zigbee switches the options are (to my understanding) what I stated above. Maybe the easiest would be that you click the edit button of the remote switch and for the actions set something like: Click: http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=1234&switchcmd=On Double-click: http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=1234&switchcmd=Off
> 
> You need to set idx= the idx of your attic switch and set the domoticz port to url correct if it is something else than 8080.
> 
> A bit like in this example I found online: ![image](https://user-images.githubusercontent.com/10372952/163368484-0eb9d675-9dcf-4a9b-b79a-9c9615d04eaa.png) In your case you should see something like "click" and "double-click" instead of "P_on", "P_off".
> 
> In any case, I do not think this is related to this plugin so better to continue e.g. in Domoticz forum 👍

Well the plugin should activate this zigbee switch in domoticz so it can be used in a scene
